// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmMX-310HihqQfn38fT2wnEEtx4V9uN4',
    appId: '1:141376676314:web:9d7248f1e165c140e460e3',
    messagingSenderId: '141376676314',
    projectId: 'qodestone-estatio',
    authDomain: 'qodestone-estatio.firebaseapp.com',
    storageBucket: 'qodestone-estatio.appspot.com',
    measurementId: 'G-2L9WV5XL4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLyYFCenKlCXbK6IGRa2zeL1DEfmA6ms',
    appId: '1:141376676314:android:c7bede22782215d7e460e3',
    messagingSenderId: '141376676314',
    projectId: 'qodestone-estatio',
    storageBucket: 'qodestone-estatio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9NQtkauVJ5Ozsa0SoKr74hs8cJgl1HoQ',
    appId: '1:141376676314:ios:c3be73a98ad0add7e460e3',
    messagingSenderId: '141376676314',
    projectId: 'qodestone-estatio',
    storageBucket: 'qodestone-estatio.appspot.com',
    androidClientId: '141376676314-apvpop74ptaov1t3af3upna2daa6vd7c.apps.googleusercontent.com',
    iosClientId: '141376676314-2lt5iepv72b0920cvf8jch8471tumt0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.estatio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9NQtkauVJ5Ozsa0SoKr74hs8cJgl1HoQ',
    appId: '1:141376676314:ios:c3be73a98ad0add7e460e3',
    messagingSenderId: '141376676314',
    projectId: 'qodestone-estatio',
    storageBucket: 'qodestone-estatio.appspot.com',
    androidClientId: '141376676314-apvpop74ptaov1t3af3upna2daa6vd7c.apps.googleusercontent.com',
    iosClientId: '141376676314-2lt5iepv72b0920cvf8jch8471tumt0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.estatio',
  );
}
